language: python
sudo: required
#dist: trusty
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
env:
  - SBPIPE=$(pwd)
install:

  # install xvfb
  # we don't have X11 on Travis-CI, so we use a virtual framebuffer
  # because R packages for generating figures were compiled with X11
  # support.
  - sudo apt-get update
  - sudo apt-get install xvfb
  - PID=$$
  # create a virtual screen and suppress the output
  - Xvfb :$PID -screen 0 800x600x16 2>/dev/null 1>&2 &
  - xvfb_pid=$!
  - export DISPLAY=:$PID.0

  # install copasi
  - wget https://github.com/copasi/COPASI/releases/download/Build-140/COPASI-4.19.140-Linux-64bit.tar.gz
  - tar xvzf COPASI-4.19.140-Linux-64bit.tar.gz
  - PATH=$PATH:$(pwd)/COPASI-4.19.140-Linux-64bit/bin/

  # install miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # install sbpipe
  # create sbpipe environment and install sbpipe dependencies
  - conda env create --name sbpipe python=$TRAVIS_PYTHON_VERSION --file environment.yaml
  - source activate sbpipe
  # install sbpipe
  - python setup.py install

# command to run tests
script:
  # Override SBpipe logging configuration
  - sed -i 's/level=INFO/level=CRITICAL/g' logging_config.ini
  - sed -i 's/level=DEBUG/level=CRITICAL/g' logging_config.ini
  - nosetests test_suite.py

