language: python
# NOTE: 14.04 uses R ggplot2 v0.9.3 instead of v2.1.0 . v0.9.3 contains some bug
# which causes an issue on some plot. Expect some error message because of this.
sudo: required
dist: trusty
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
env:
  - SBPIPE=$(pwd)
install:
  - sudo apt update

  # THIS WORKS but causes a lot of output
  # we don't have X11, so we use a virtual framebuffer
#  - sudo apt install xvfb
#  - PID=$$
#  - Xvfb :$PID -screen 0 800x600x16 &
#  - xvfb_pid=$!
#  - export DISPLAY=:$PID.0

  - sudo apt libcairo2-dev libjpeg9-dev


  # install copasi
  - wget https://github.com/copasi/COPASI/releases/download/Build-140/COPASI-4.19.140-Linux-64bit.tar.gz
  - tar xvzf COPASI-4.19.140-Linux-64bit.tar.gz
  - PATH=$PATH:$(pwd)/COPASI-4.19.140-Linux-64bit/bin/

  # Set up miniconda - for some reason, there is some missing package (fonts to install maybe).
  # For now, we use anaconda instead.
  # miniconda files
      #wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      #wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/archive/Anaconda2-4.3.1-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/archive/Anaconda3-4.3.1-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # create sbpipe environment and install sbpipe dependencies
  - conda env create --name sbpipe python=$TRAVIS_PYTHON_VERSION --file environment.yaml
  - source activate sbpipe
  # install sbpipe
  - python setup.py install
# command to run tests
script:
  # Override SBpipe logging configuration
  #- sed -i 's/level=INFO/level=CRITICAL/g' logging_config.ini
  - sed -i 's/level=DEBUG/level=CRITICAL/g' logging_config.ini
  - nosetests test_suite.py


### OLD TRAVIS FILE explicitly installing Python, R, and LaTeX packages
#
#language: python
## NOTE: 14.04 uses R ggplot2 v0.9.3 instead of v2.1.0 . v0.9.3 contains some bug
## which causes an issue on some plot. Expect some error message because of this.
#sudo: required
#dist: trusty
#python:
#  - "2.7"
#  - "3.4"
#env:
#  - SBPIPE=$(pwd)
## necessary for installing Python dependencies
##virtualenv:
##  system_site_packages: true
#before_install:
#  - sudo add-apt-repository ppa:marutter/rrutter -y
#  - sudo apt-get update -q
#  - sudo apt-get -y --force-yes install r-base r-base-dev
#  - sudo apt-get -y --force-yes --no-install-recommends install texlive-latex-base texlive-latex-recommended
#install:
#  # install other dependencies
#
#  # install copasi
#  - wget https://github.com/copasi/COPASI/releases/download/Build-140/COPASI-4.19.140-Linux-64bit.tar.gz
#  - tar xvzf COPASI-4.19.140-Linux-64bit.tar.gz
#  - PATH=$PATH:$(pwd)/COPASI-4.19.140-Linux-64bit/bin/
#
#  # install R dependencies
#  - mkdir -p $(pwd)/r_libs/
#  - export R_LIBS_USER=$(pwd)/r_libs/
#  - Rscript install_rdeps.r
#
#  # install python dependencies
#  # Travis-CI does not accept "--user" option within the pip command.
#  # So use the standard pip install command instead.
#  #- python install_pydeps.py
#  - pip install -r requirements.txt
#
#  # install sbpipe
#  - python setup.py install
## command to run tests
#script:
#  # Override SBpipe logging configuration
#  - sed -i 's/level=INFO/level=CRITICAL/g' logging_config.ini
#  - sed -i 's/level=DEBUG/level=CRITICAL/g' logging_config.ini
#  - nosetests test_suite.py
